config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/welcome' => 'welcome#new'

  # get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  get '/auth/:provider/callback', :to => 'sessions#create'
  get 'auth/failure', to: redirect('/welcome')
  get 'signout/:id', :to => 'sessions#destroy', as: "signout"
  # get '/login', :to => 'sessions#new', :as => :login 
  # match '/auth/failure', to: redirect('/welcome')
  # get 'auth/google_oauth2', to: 'sessions#create'

  post '/stores/:store_id/products/:product_id/reviews/:id', to: 'reviews#update'


  get '/delete_review' => 'reviews#destroy'

  jsonapi_resources :stores do 
    jsonapi_resources :products do 
      jsonapi_resources :reviews, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    end 
  end 


  jsonapi_resources :sessions, only: [:new, :create]

  post 'users/:id', to: 'users#update'

  jsonapi_resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  
  get '/reviews/:id', to: 'reviews#show'

 resources :notes
 get '/delete_note' => 'notes#destroy'

end

app/models/store.rb
class Store < ApplicationRecord
    serialize :hours_of_operation, Array
 
    has_many :products

    def remove_duplicates(store_id)
        store = Store.find_by(id: store_id)

        grouped_products = store.products.group_by{|name| name}

        grouped_products.values.map do |duplicate|
            duplicate.uniq 
        end 
    end


end

app/controllers/stores_controller.rb
require 'omniauth'
class StoresController < JSONAPI::ResourceController

    def index 
        if @user = User.find_by(id: session[:user_id])
            Api.new.stores
            Store1.new.products
            Store2.new.products
            Store3.new.products
            Store4.new.products
            Store5.new.products
            Store6.new.products
            Store7.new.products
            Store8.new.products
            Store9.new.products
            Store10.new.products
            Store11.new.products
            Store12.new.products
            Store13.new.products
            Store14.new.products             
            Store15.new.products
            Store16.new.products
            Store17.new.products
            Store18.new.products
            Store19.new.products
            Store20.new.products
            Store21.new.products
            Store22.new.products
            Store23.new.products
            Store24.new.products
            Store25.new.products

            @stores = Store.all 
        else 
            flash[:notice] = "Please log in."
            redirect_to new_session_path
        end 
    end

    def show 
        if @user = User.find_by(id: session[:user_id])
            @store = Store.find_by(id: params["id"])
        else 
            flash[:notice] = "Please log in."
            redirect_to new_session_path
        end 
    end

end

app/views/stores/index.html.erb
<br></br>
<h1>Here is what we have in store for you, <%= @user.first_name %>!</h1>
<%= link_to "My Account", user_path(@user)  %><br></br>
<br></br>
<% @stores.each do |store| %>
    <% unless store.products.empty? %>
        <h2> <%= link_to store.name, store_path(store) %> <h2>

        <h3> Come visit us: </h3>
        <%= store.address_line_1 %><br>
        <% if store.address_line_2 != nil %>
            <%= store.address_line_2 %><br>
        <% end %>
        <%= store.city %><br>
        <%= store.zipcode %><br>

        <h3> Any questions? Call us: </h3>
        <%= store.phone_number %>

        <h3> Hours of Operation: </h3>
            Sunday: <%= store.hours_of_operation[0][0] %> - <%= store.hours_of_operation[0][1] %><br>
            <% if store.hours_of_operation[1][0] == nil && store.hours_of_operation[1][1] == nil %>
                Monday: closed <br>
            <% elsif store.hours_of_operation[1][0] == 0000 && store.hours_of_operation[1][1] == 0000 %>
                Monday: closed <br>
            <% else %>
                Monday: <%= store.hours_of_operation[1][0] %> - <%= store.hours_of_operation[1][1] %><br>
            <% end %>
            Tuesday: <%= store.hours_of_operation[2][0] %> - <%= store.hours_of_operation[2][1] %><br>
            Wednesday: <%= store.hours_of_operation[3][0] %> - <%= store.hours_of_operation[3][1] %><br>
            Thursday: <%= store.hours_of_operation[4][0] %> - <%= store.hours_of_operation[4][1] %><br>
            Friday: <%= store.hours_of_operation[5][0] %> - <%= store.hours_of_operation[5][1] %><br>
            Saturday: <%= store.hours_of_operation[6][0] %> - <%= store.hours_of_operation[6][1] %><br>

        <h3>FAQs</h3>
            <% if store.bilingual == true %>
                <p> Are staff bilingual? Yes. </p>
            <% else %>
                <p> Are staff bilingual? No. </p>
            <% end %>

            <% if store.tasting_bar == true %>
                <p> Is there a tasting bar? Yes. </p>
            <% else %>
                <p> Is there a tasting bar? No. </p>
            <% end %>

            <% if store.public_transport == true %>
                <p> Is it accessible via public transportation? Yes. </p>
            <% else %>
                <p> Is it accessible via public transportation? No.  </p>
            <% end %>

        <br></br>
        <br></br>
    <% end %>
<% end %>

app/views/stores/show.html.erb
<%= link_to "Go Back to the All Shops", stores_path  %><br></br>
<%= link_to "My Account", user_path(@user)  %><br></br>

<h3> Come visit us: </h3>
<%= @store.address_line_1 %><br>
<% if @store.address_line_2 != nil %>
    <%= @store.address_line_2 %><br>
<% end %>
<%= @store.city %><br>
<%= @store.zipcode %><br>

<h3> Any questions? Call us: </h3>
<%= @store.phone_number %>

<h3> Hours of Operation: </h3>
    Sunday: <%= @store.hours_of_operation[0][0] %> - <%= @store.hours_of_operation[0][1] %><br>
    <% if @store.hours_of_operation[1][0] == nil && @store.hours_of_operation[1][1] == nil %>
        Monday: closed <br>
    <% elsif @store.hours_of_operation[1][0] == 0000 && @store.hours_of_operation[1][1] == 0000 %>
        Monday: closed <br>
    <% else %>
        Monday: <%= @store.hours_of_operation[1][0] %> - <%= @store.hours_of_operation[1][1] %><br>
    <% end %>
    Tuesday: <%= @store.hours_of_operation[2][0] %> - <%= @store.hours_of_operation[2][1] %><br>
    Wednesday: <%= @store.hours_of_operation[3][0] %> - <%= @store.hours_of_operation[3][1] %><br>
    Thursday: <%= @store.hours_of_operation[4][0] %> - <%= @store.hours_of_operation[4][1] %><br>
    Friday: <%= @store.hours_of_operation[5][0] %> - <%= @store.hours_of_operation[5][1] %><br>
    Saturday: <%= @store.hours_of_operation[6][0] %> - <%= @store.hours_of_operation[6][1] %><br>

<h3>FAQs</h3>
    <% if @store.bilingual == true %>
        <p> Are staff bilingual? Yes. </p>
    <% else %>
        <p> Are staff bilingual? No. </p>
    <% end %>

    <% if @store.tasting_bar == true %>
        <p> Is there a tasting bar? Yes. </p>
    <% else %>
        <p> Is there a tasting bar? No. </p>
    <% end %>

    <% if @store.public_transport == true %>
        <p> Is it accessible via public transportation? Yes. </p>
    <% else %>
        <p> Is it accessible via public transportation? No.  </p>
    <% end %>

<br></br>
<br></br>


<% @store.products.each do |product| %>

    <img src=" <%=product.image%> "><br>
    Name: <%= product.name %><br>
    Alcohol Content: <%= product.alcohol_content * 0.01 %><br>
    Price (in Canadian dollars): <%= product.price_in_cents * 0.01 %><br>
    Variety: <%= product.variety %><br>
    Style: <%= product.style %><br>
    Brewery/Winery/Distillery: <%= product.producer_name %><br>
    Flavor Profile: <%= product.flavor_profile %><br>
    Suggestion: <%= product.serving_suggestion %><br>
    <%= link_to "See what customers think!", store_product_path(@store, product) %><br>
    <br></br>

<% end %>