config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/welcome' => 'welcome#new'

  # get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  get '/auth/:provider/callback', :to => 'sessions#create'
  get 'auth/failure', to: redirect('/welcome')
  get 'signout/:id', :to => 'sessions#destroy', as: "signout"
  # get '/login', :to => 'sessions#new', :as => :login 
  # match '/auth/failure', to: redirect('/welcome')
  # get 'auth/google_oauth2', to: 'sessions#create'

  post '/stores/:store_id/products/:product_id/reviews/:id', to: 'reviews#update'


  get '/delete_review' => 'reviews#destroy'

  jsonapi_resources :stores do 
    jsonapi_resources :products do 
      jsonapi_resources :reviews, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    end 
  end 


  jsonapi_resources :sessions, only: [:new, :create]

  post 'users/:id', to: 'users#update'

  jsonapi_resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  
  get '/reviews/:id', to: 'reviews#show'

 resources :notes
 get '/delete_note' => 'notes#destroy'

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :notes

    has_many :reviews
    has_many :products, through: :reviews

    validates :username, presence: true 
    validates :username, uniqueness: true 

    def self.logged_in?
        @user ||= User.find_by_id(session[:user_id])
    end

    def self.access_permitted? 
        unless self.logged_in? 
            flash[:danger] = "Please log in."
            redirect_to new_session_path
        end
    end

    def self.users_and_reviews 
        @users = self.all
        @users.each do |user|
            binding.pry 
            user.the_reviews = []
            user.reviews.each do |review|
                user.the_reviews << review
            end 
        end 
    end 


end

app/controllers/users_controller.rb
require 'omniauth'
class UsersController < JSONAPI::ResourceController
    skip_before_action :verify_authenticity_token

    def index 
        @user = User.find_by(id: 3)
        # @users = User.all.as_json
        @users = User.all
        # gon.all_users = @users

        respond_to do |format|
            format.html { render :index }
            format.json { render json: @users, status: 201}
        end
    end 

    def new 
        @user = User.new
    end 

    def create 
        user = User.new(user_params)
        user.update(login_params)

        if user.save
            session[:user_id] = user.id 
            flash[:update] = "Successfully created an account."
            redirect_to user_url(user)
        elsif user.username.blank? || user.first_name.blank? || user.last_name.blank? || user.password.blank? || user.password_confirmation.blank?
            flash[:update] = "The form must be completed to create a new account. Please fill all entries."
            redirect_to new_user_url
        elsif !user.authenticate(user_params) 
            flash[:update] = "Password and password confirmation do not match."
            redirect_to new_user_url 
        else 
            flash[:update] = "We could not create an account at this time. Please try again later."
            redirect_to new_user_url 
        end
    end 

    def show
        @user = User.find(session[:user_id])
        @note = Note.new 
        
        @user.reviews.each do |review|
            @product = review.product 
            @store = @product.store 
        end 

        respond_to do |format|
            format.html { render :show }
            format.json { render json: @user }
        end 

    end

    def edit 
        @user = User.find(params["id"])
    end

    def update 

        @user = User.find_by(id: session[:user_id])

        if @user
            @user.update(user_params)
            redirect_to user_path(@user) 
        else 
            redirect_to edit_user_path(@user)
        end 
    end

    private 

    def user_params 
        params.require(:user).permit(:first_name, :last_name, :username)
    end

    def login_params
        params.require(:user).permit(:identification, :password, :password_confirmation)
    end

end

app/helpers/users_helper.rb
module UsersHelper 

    def logged_in?
        @user ||= User.find_by_id(session[:user_id])
    end

    def access_permitted? 
        unless self.logged_in? 
            flash[:danger] = "Please log in."
            redirect_to new_session_path
        end
    end

end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

    <%= f.label :first_name %>
    <%= f.text_field :first_name %><br></br>

    <%= f.label :last_name %>
    <%= f.text_field :last_name %><br></br>

    <%= f.label :username  %>
    <%= f.text_field :username %><br></br>

    <%= f.label :password %>
    <%= f.password_field :password %><br></br>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %><br></br>

    <%= f.submit %>
<% end %>

app/views/users/_users.html.erb
<p> <strong> User: </strong> <%= u.username %>, a.k.a. <i> <%= u.first_name %></i></p>
<p> <strong> Joined: </strong> <%= u.created_at.strftime("%B %d %Y")%></p>
<button id="reviews"> <%= u.first_name %>'s Reviews </button><br></br>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>

    <%= f.label :username  %>
    <%= f.text_field :username %><br></br>

    <%= f.label :first_name %>
    <%= f.text_field :first_name %><br></br>

    <%= f.label :last_name %>
    <%= f.text_field :last_name %><br></br>

    <%= f.button "Update User Info", { :controller => 'users', :action => 'update'} %>
<% end %>

app/views/users/index.html.erb
<h2> Meet People </h2><br>
    <div id="allUsers">
    <h3><strong> User: </strong> <%= @user.username %>, a.k.a. <i> <%= @user.first_name %></i></h3>
    <p> Joined on <%= @user.created_at.strftime("%B %d %Y")%></p>

    <% @user.reviews.each do |review| %>
        <div id="review-<%= review.id%>"><strong><%= review.product.name %> beer: </strong><%= truncate review.product_review %></div>
            <button class="js-review" data-id="<%= review.id %>"> More... </button><br><br>
    <% end %>
    <br></br>
    </div>

    <button id="users-btn">See more users...</button>

<%= content_tag :div, class: "users", data: {users: @users} do %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" ></script>
<script>
   $(function () {
       $(".js-review").on('click', function() {
           const id = $(this).data("id");
           const $element = $(this);

           $.get("/reviews/" + id, function(data) {
                $("#review-"+id).text(data);
                $element.remove();
           });
       });
       $("#users-btn").on('click', function() {
           $("#allUsers").html("");
           $.get('/users.json', function(users){
                users.forEach(function (user) {
                    let eachUser = new User(user.username, user.first_name, user.reviews);
                    $("#allUsers").append(eachUser.renderUser());
                    $("#allUsers").append(eachUser.renderReviews());
                });
           })
           
       }); 

       function User(userName, firstName, reviews){
        this.userName = userName; 
        this.firstName = firstName; 
        this.reviews = reviews;
       };

       User.prototype.renderUser = function() {
        return `<br><h3><strong> User: </strong> ${this.userName}, a.k.a. <i> ${this.firstName} </i></h3>`
       };

       User.prototype.renderReviews = function() {
           let htmlString = "";
            this.reviews.forEach(function (review) {
                htmlString += `<p><strong>${review.product_name} Beer:</strong>${review.product_review}</p>`
            });
            return htmlString;
       };

   });
</script>
<% end %>   

app/views/users/new.html.erb
<h3> Create Your User Account: </h3>

<% if flash[:update] %>
    <div class="notice"><%= flash[:update] %><br></br></div>
<% end %>

<%= render 'form' %>

app/views/users/show.html.erb
<h2> Welcome <%= @user.first_name %>! </h2>

<%= link_to "Explore Restaurants", stores_path(:user_id => @user.id) %><br></br>

<%= link_to "Log out", signout_path(@user) %><br></br>

<% if flash[:account_success] %>
    <div class="notice"><%= flash[:account_success] %></div>
<% end %>

<h3>Your Account Info:</h3>

<strong> Username: </strong> <%= @user.username %><br>
<strong> First Name: </strong> <%= @user.first_name %><br> 
<strong> Last Name: </strong> <%= @user.last_name %><br> 
<strong> You joined us on: </strong> <%= @user.created_at.strftime("%B %d %Y") %> <br><br>

<%= link_to "Edit Your Account Info", edit_user_path(@user) %><br></br>
<%= link_to "See what other users think", users_path %><br><br>

<br></br>
<%= form_for @note, :url => { :controller => "notes", :action => "create"}, :html => {:method => :post} do |f| %>
    <%= f.label "Note to self:" %>
    <%= f.text_field :content %>
  
    <%= f.submit %>
  <% end %>
  <br></br>
  
  <div id="notes">
    <% @user.notes.each do |note| %>
        <div id="the-note-<%=note.id%>">
            <div><%= note.content %></div>
            <div id="delete-<%=note.id%>"><button class="deleteButton" data-id="<%= note.id %>" >Delete</button></div><br>
        </div>
    <% end %>
  </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" ></script>
<script>
   $(function () {
       $(".deleteButton").on('click', function() {
           const id = $(this).data("id");
           const $element = $(this);
           $.ajax({
               url: "/notes/" + id,
               type: 'DELETE',
               success:function(id) {
                $element.remove(),
                $("#the-note-" + id).remove();
               }
           })
       });

   });

</script>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" ></script>
  <script type="text/javascript" charset="utf-8">
  $(function () {
    $('form').submit(function(event) {
        event.preventDefault();
        const values = $(this).serialize();
        const posting = $.post("/notes", values);
        
        posting.done(function(data) {
            const note = new Note(data.content);
            $("#notes").append(`<p> ${note.content} </p>`)
            $("#notes").append(`<div id=delete-${note.id}><button class="deleteButton" data-id=${note.id}>Delete</button></div>`)
        });
    });

    class Note {
        constructor(content) {
            this.content = content
        }
    }

  });
  </script>

<% if flash[:update_review] %>
    <div class="notice"><%= flash[:update_review] %></div>
<% end %>

<h3>Your Reviews:</h3>
<% @user.reviews.newest_first.each do |review| %>
    <strong>Business: </strong> <%= review.product.store.name %><br>
    <strong>Product: </strong> <%= review.product.name %><br>
    <div id="review-<%= review.id%>"><strong>Review: </strong><%= truncate review.product_review %></div>
    <button class="js-review" data-id="<%= review.id %>"> More... </button><br><br>
    
    <%= link_to "Edit this Review", edit_store_product_review_path(@store, @product, review) %><br>
    <%= link_to "Delete this Review", delete_review_path(review) %><br></br>

    <%= hidden_field_tag "user_id", @user.id %>
<% end %>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" ></script>
<script>
   $(function () {
       $(".js-review").on('click', function() {
           const id = $(this).data("id");
           $.get("/reviews/" + id, function(data) {
                $("#review-" + id).text(data);
           });
       });
   });

</script>

app/views/users/testing.html.erb
<h2> Meet People </h2><br>
    <div id="users">
    <h3><strong> User: </strong> <%= @user.username %>, a.k.a. <i> <%= @user.first_name %></i></h3>
    <p> Joined on <%= @user.created_at.strftime("%B %d %Y")%></p>

    <% @user.reviews.each do |review| %>
        <div id="review-<%= review.id%>"><strong><%= review.product.name %> beer: </strong><%= truncate review.product_review %></div>
            <button class="js-review" data-id="<%= review.id %>"> More... </button><br><br>
    <% end %>
    <br></br>
    </div>

    <button id="users-btn">See more users...</button>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" ></script>
<script>
   $(function () {
       $(".js-review").on('click', function() {
           var id = $(this).data("id");
           $.get("/reviews/" + id, function(data) {
                $("#review-"+id).text(data);
           });
       });

       $("#users-btn").on('click', function() {
           $("#users").html("");

           $.get("/users.json", function(users) {
               users.forEach(function (user) {
                   let eachUser = new User(user.username, user.first_name, user.reviews)
                   $("#users").append(eachUser.renderUser())
               });
           });
       }); 

       function User(userName, firstName, reviews){
        this.userName = userName; 
        this.firstName = firstName; 
        this.reviews = reviews;
       };

       User.prototype.renderUser = function() {

       const usersNames =  `<h3><strong> User: </strong> ${this.userName}, a.k.a. <i> ${this.firstName} </i></h3>
        <p><strong>Reviews:</strong> ${this.reviews.length} </p><br> `

            this.reviews.forEach(function(review) {
                const usersReviews = `<p><strong>review.product_name</strong>review.product_review</p>`
                const usersInfo = usersNames.concat(usersReviews);
            });
            return usersInfo;
       };

   });
</script>