config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/welcome' => 'welcome#new'

  # get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  get '/auth/:provider/callback', :to => 'sessions#create'
  get 'auth/failure', to: redirect('/welcome')
  get 'signout/:id', :to => 'sessions#destroy', as: "signout"
  # get '/login', :to => 'sessions#new', :as => :login 
  # match '/auth/failure', to: redirect('/welcome')
  # get 'auth/google_oauth2', to: 'sessions#create'

  post '/stores/:store_id/products/:product_id/reviews/:id', to: 'reviews#update'


  get '/delete_review' => 'reviews#destroy'

  jsonapi_resources :stores do 
    jsonapi_resources :products do 
      jsonapi_resources :reviews, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    end 
  end 


  jsonapi_resources :sessions, only: [:new, :create]

  post 'users/:id', to: 'users#update'

  jsonapi_resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  
  get '/reviews/:id', to: 'reviews#show'

 resources :notes
 get '/delete_note' => 'notes#destroy'

end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :store

    has_many :reviews 
    has_many :users, through: :reviews 

end

app/controllers/products_controller.rb
require 'omniauth'
class ProductsController < JSONAPI::ResourceController 

    def show 
        if @user = User.find_by(id: session[:user_id])
            @store = Store.find(params["store_id"])
            @product = Product.find(params["id"])
        else 
            flash[:notice] = "Please log in."
            redirect_to new_session_path
        end 
    end

end

app/views/products/show.html.erb
<h3>Brewed by: <%= @product.producer_name %> </h3>

<%= link_to "Go Back to the Beer Menu", store_path(@store)  %><br></br>
<%= link_to "My Account", user_path(@user)  %><br></br>

<h3> <%= @product.name %> </h3><br>

<img src=" <%=@product.image%> "><br>
<i>Alcohol Content: </i><%= @product.alcohol_content * 0.01 %><br>
<i>Price (in Canadian dollars): </i><%= @product.price_in_cents * 0.01 %><br>
<i>Variety: </i><%= @product.variety %><br>
<i>Style: </i><%= @product.style %><br>
<i>Flavor Profile: </i><%= @product.flavor_profile %><br>
<i>Suggestion: </i><%= @product.serving_suggestion %><br>
<br>

<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>

<% if @product.reviews.empty? %>
    <p> It looks like there are no reviews yet. </p>
    <p> <%= link_to "Be the first to review this product!",  new_store_product_review_path(@store, @product, @review)  %></p>
    <%= hidden_field_tag "user_id", @user_id %>
<% else %>
    <h3>User Reviews:</h3>
    <% @product.reviews.each do |review| %>
        <p>
         <strong> <%= review.user.username %> says: </strong> 
            <div id="review-<%= review.id %>">
                <%= truncate review.product_review %><br></div> <button class="js-review" data-id="<%= review.id %>">More...</button><br></br>
         <i>posted on <%= review.created_at.strftime("%B %d %Y") %></i>
         </p>

    <% end %>
    <p> <%= link_to "Share Your Experience!",  new_store_product_review_path(@store, @product, @review)  %></p>
<% end %>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" ></script>
<script type="text/javascript" charset="utf-8">
    $(function () {
        $(".js-review").on('click', function() {
            var id = $(this).data("id");
            $.get("/reviews/" + id, function(data) {
                $("#review-" + id).text(data);
            });
        });
    });
</script>